### ISSUE TITLE
Can not install DotEditor on Ubuntu 16.04: ImportError: /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1: undefined symbol: drmFreeDevice

### ISSUE THREAD

**Issue by miksask** [vincenthEE/DotEditor#16]
I have some problems with the installation of the package

Here is error message:

```
shurph:$ ./DotEditor-0.3.1-linux 
Traceback (most recent call last):
  File "<string>", line 18, in <module>
  File "/usr/lib/python2.7/site-packages/PyInstaller/loader/pyi_importers.py", line 270, in load_module
  File "/home/vincent/DotEditor/build/pyinstaller_win/out00-PYZ.pyz/wx", line 45, in <module>
  File "/usr/lib/python2.7/site-packages/PyInstaller/loader/pyi_importers.py", line 270, in load_module
  File "/home/vincent/DotEditor/build/pyinstaller_win/out00-PYZ.pyz/wx._core", line 4, in <module>
  File "/usr/lib/python2.7/site-packages/PyInstaller/loader/pyi_importers.py", line 409, in load_module
ImportError: /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1: undefined symbol: drmFreeDevice
```

My environment:
```
shurph:$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.1 LTS"

shurph:$ cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.1 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.1 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

shurph:$ python --version
Python 2.7.12

```

**Comment by vporton** [comment]
The same trouble in Debian "stretch".

**Comment by dundalek** [comment]
I had the same issue. I was able to run it from source.

First install dependencies:
```
sudo apt install python-wxgtk2.8 python-wxtools python-ply
sudo pip install colour
```
Then fetch and run the code:
```
git clone https://github.com/vincenthEE/DotEditor.git
cd DotEditor
python DotEditor.py
```

**Comment by cleeland** [comment]
Probably the same as this issue: https://github.com/fman-users/fman/issues/119
